import { ButtonStyle, PermissionFlagsBits } from 'discord.js';
import { button, panel, v2 } from '../components/ui.js';
import { ensureGuild, one, run } from '../database/index.js';
import { dashboardStats, analytics, track } from '../modules/analytics/index.js';
import { answerWithKnowledge } from '../services/ai.js';
import { addKnowledge, removeKnowledge, searchKnowledge } from '../modules/knowledge/index.js';
import { createTicket, ticketByChannel, listTickets, claimTicket, closeTicket } from '../modules/tickets/index.js';
import { createEvent, eventById, rsvpStats, setRsvp, upcoming } from '../modules/events/index.js';
import { audit } from '../services/audit.js';
import { canModerate, requirePermission } from '../utils/permissions.js';
import { allow } from '../utils/rate-limit.js';
import { logger } from '../utils/logger.js';
const admin = (interaction) => { if (!requirePermission(interaction, PermissionFlagsBits.ManageGuild)) throw new Error('You need the **Manage Server** permission.'); };
function eventPanel(event) { const totals = Object.fromEntries(rsvpStats(event.id).map((row) => [row.response, row.count])); return panel(`📅 ${event.title}`, `${event.description}\n\n**Starts:** <t:${Math.floor(new Date(event.starts_at).getTime() / 1000)}:F>\n**RSVPs:** ${totals.attend ?? 0} attending · ${totals.maybe ?? 0} maybe · ${totals.decline ?? 0} declined`, [button(`event:${event.id}:attend`, 'Attend', ButtonStyle.Success), button(`event:${event.id}:maybe`, 'Maybe'), button(`event:${event.id}:decline`, 'Decline', ButtonStyle.Danger), button(`event:${event.id}:remind`, 'Remind me')]); }
function ticketPanel(ticket) { return panel(`🎫 TICKET #${ticket.id}`, `**Category:** ${ticket.category}\n**Priority:** ${ticket.priority.toUpperCase()}\n**Status:** ${ticket.status.toUpperCase()}\n**Assigned:** ${ticket.assignee_id ? `<@${ticket.assignee_id}>` : 'Unassigned'}\n**Subject:** ${ticket.subject}`, [button(`ticket:${ticket.id}:claim`, 'Claim', ButtonStyle.Primary), button(`ticket:${ticket.id}:close`, 'Close', ButtonStyle.Danger)]); }
export async function onInteraction(interaction) {
  if (!interaction.inGuild()) return interaction.reply(v2([panel('NEXUS', 'NEXUS commands are available inside Discord servers.')], true));
  ensureGuild(interaction.guildId);
  try {
    if (interaction.isChatInputCommand()) {
      if (!allow(`command:${interaction.guildId}:${interaction.user.id}`)) throw new Error('You are using NEXUS too quickly. Please wait a moment.');
      track(interaction.guildId, 'command', { userId: interaction.user.id });
      const group = interaction.options.getSubcommandGroup(false); const sub = interaction.options.getSubcommand(false);
      if (interaction.commandName === 'nexus' && sub === 'dashboard') { admin(interaction); const stats = dashboardStats(interaction.guildId); const next = stats.event ? `**Next event:** ${stats.event.title} · <t:${Math.floor(new Date(stats.event.starts_at).getTime() / 1000)}:R>` : '**Next event:** none scheduled'; return interaction.reply(v2([panel('NEXUS CONTROL CENTER', `**Security:** ACTIVE\n**Open tickets:** ${stats.tickets}\n**Members:** ${interaction.guild.memberCount.toLocaleString()}\n${next}\n**Messages tracked (7d):** ${stats.messages}`, [button('dashboard:security', 'Security'), button('dashboard:tickets', 'Tickets'), button('dashboard:analytics', 'Analytics'), button('dashboard:events', 'Events')])], true)); }
      if (interaction.commandName === 'nexus' && sub === 'ask') { await interaction.deferReply(v2([], true)); const answer = await answerWithKnowledge(interaction.guildId, interaction.options.getString('question', true)); return interaction.editReply(v2([panel('NEXUS AI ASSISTANT', answer)], true)); }
      if (interaction.commandName === 'nexus' && group === 'knowledge') { admin(interaction); if (sub === 'add') { const id = addKnowledge(interaction.guildId, interaction.user.id, { title: interaction.options.getString('title', true), content: interaction.options.getString('content', true), category: interaction.options.getString('category') ?? 'general' }); audit(interaction.guildId, 'knowledge:add', { actorId: interaction.user.id, targetId: String(id) }); return interaction.reply(v2([panel('Knowledge saved', `Entry **#${id}** is now available to the approved AI knowledge base.`)], true)); } if (sub === 'search') { const rows = searchKnowledge(interaction.guildId, interaction.options.getString('query', true)); return interaction.reply(v2([panel('Knowledge search', rows.length ? rows.map((r) => `**#${r.id} · ${r.title}** (${r.category})\n${r.content.slice(0, 300)}`).join('\n\n') : 'No approved knowledge entries found.')], true)); } const deleted = removeKnowledge(interaction.guildId, interaction.options.getInteger('id', true)); return interaction.reply(v2([panel('Knowledge deletion', deleted ? 'Entry deleted.' : 'No entry found.')], true)); }
      if (interaction.commandName === 'nexus' && sub === 'analytics') { admin(interaction); const rows = analytics(interaction.guildId); return interaction.reply(v2([panel('NEXUS ANALYTICS', rows.length ? rows.map((r) => `**${r.kind}:** ${r.count}`).join('\n') : 'No tracked activity exists yet. Metrics appear as members use the server.')], true)); }
      if (interaction.commandName === 'ticket' && sub === 'open') { await interaction.deferReply(v2([], true)); const ticket = await createTicket(interaction, { category: interaction.options.getString('category', true), subject: interaction.options.getString('subject', true), priority: interaction.options.getString('priority') ?? 'normal' }); await ticket.channel.send(v2([ticketPanel({ id: ticket.id, category: interaction.options.getString('category', true), priority: interaction.options.getString('priority') ?? 'normal', status: 'open', assignee_id: null, subject: interaction.options.getString('subject', true) })])); return interaction.editReply(v2([panel('Ticket created', `Your private support channel is ${ticket.channel}.`)], true)); }
      if (interaction.commandName === 'ticket' && sub === 'list') { admin(interaction); const rows = listTickets(interaction.guildId); return interaction.reply(v2([panel('Open tickets', rows.length ? rows.map((t) => `**#${t.id}** · ${t.priority.toUpperCase()} · <#${t.channel_id}>`).join('\n') : 'No open tickets.')], true)); }
      if (interaction.commandName === 'event' && sub === 'create') { admin(interaction); const startsAt = new Date(interaction.options.getString('when', true)); if (Number.isNaN(startsAt.getTime()) || startsAt <= new Date()) throw new Error('Use a future ISO-8601 UTC date, such as `2026-12-31T20:00:00Z`.'); const id = createEvent(interaction.guildId, interaction.channelId, interaction.user.id, { title: interaction.options.getString('title', true), description: interaction.options.getString('description', true), startsAt: startsAt.toISOString() }); const event = eventById(id); await interaction.reply(v2([eventPanel(event)])); const message = await interaction.fetchReply(); run('UPDATE events SET message_id = ? WHERE id = ?', [message.id, id]); return; }
      if (interaction.commandName === 'event' && sub === 'upcoming') { const rows = upcoming(interaction.guildId); return interaction.reply(v2([panel('Upcoming events', rows.length ? rows.map((e) => `**#${e.id} · ${e.title}** — <t:${Math.floor(new Date(e.starts_at).getTime() / 1000)}:R>`).join('\n') : 'No scheduled events.')], true)); }
      if (interaction.commandName === 'moderate') { if (!requirePermission(interaction, PermissionFlagsBits.ModerateMembers)) throw new Error('You need the **Moderate Members** permission.'); const target = await interaction.guild.members.fetch(interaction.options.getUser('member', true).id); if (!canModerate(interaction.member, target, interaction.guild)) throw new Error('You cannot moderate that member due to role hierarchy.'); const reason = interaction.options.getString('reason') ?? 'No reason provided'; if (sub === 'timeout') await target.timeout(interaction.options.getInteger('minutes', true) * 60_000, reason); audit(interaction.guildId, `moderation:${sub}`, { actorId: interaction.user.id, targetId: target.id, metadata: { reason } }); return interaction.reply(v2([panel(`Member ${sub === 'timeout' ? 'timed out' : 'warned'}`, `${target} — ${reason}`)], true)); }
      if (interaction.commandName === 'notifications') { const preference = one('SELECT * FROM notification_preferences WHERE guild_id = ? AND user_id = ?', [interaction.guildId, interaction.user.id]); const p = preference ?? { event_notifications: 1, announcement_notifications: 1, level_notifications: 0 }; return interaction.reply(v2([panel('🔔 NOTIFICATION CENTER', `**Events:** ${p.event_notifications ? 'ON' : 'OFF'}\n**Announcements:** ${p.announcement_notifications ? 'ON' : 'OFF'}\n**Level ups:** ${p.level_notifications ? 'ON' : 'OFF'}`, [button('notifications:events', 'Toggle events'), button('notifications:announcements', 'Toggle announcements'), button('notifications:levels', 'Toggle levels')])], true)); }
    }
    if (interaction.isButton()) {
      const [scope, identifier, action] = interaction.customId.split(':');
      if (scope === 'ticket') { const ticket = ticketByChannel(interaction.channelId); if (!ticket || String(ticket.id) !== identifier) throw new Error('This ticket panel is no longer active.'); if (action === 'claim') claimTicket(interaction, ticket); if (action === 'close') { closeTicket(interaction, ticket); await interaction.channel.permissionOverwrites.edit(ticket.opener_id, { SendMessages: false }); } const updated = ticketByChannel(interaction.channelId); return interaction.update(v2([ticketPanel(updated)])); }
      if (scope === 'event') { const event = eventById(identifier); if (!event || event.status !== 'scheduled') throw new Error('This event is no longer active.'); if (action === 'remind') run('INSERT INTO rsvps (event_id,user_id,response,remind) VALUES (?, ?, ?, 1) ON CONFLICT(event_id,user_id) DO UPDATE SET remind = 1', [event.id, interaction.user.id, 'maybe']); else setRsvp(event.id, interaction.user.id, action); return interaction.update(v2([eventPanel(event)])); }
      if (scope === 'notifications') { const columns = { events: 'event_notifications', announcements: 'announcement_notifications', levels: 'level_notifications' }; const column = columns[identifier]; run(`INSERT INTO notification_preferences (guild_id,user_id) VALUES (?, ?) ON CONFLICT(guild_id,user_id) DO NOTHING`, [interaction.guildId, interaction.user.id]); run(`UPDATE notification_preferences SET ${column} = CASE ${column} WHEN 1 THEN 0 ELSE 1 END WHERE guild_id = ? AND user_id = ?`, [interaction.guildId, interaction.user.id]); return interaction.reply({ content: 'Preference updated. Run `/notifications` to view current settings.', ephemeral: true }); }
      if (scope === 'dashboard') return interaction.reply({ content: `Open the matching NEXUS command: ${identifier === 'analytics' ? '`/nexus analytics`' : identifier === 'events' ? '`/event upcoming`' : identifier === 'tickets' ? '`/ticket list`' : '`/nexus dashboard`'}.`, ephemeral: true });
    }
  } catch (error) { logger.error('Interaction failed', error); const payload = v2([panel('NEXUS', `⚠️ ${error.message ?? 'An unexpected error occurred.'}`)], true); if (interaction.deferred || interaction.replied) await interaction.editReply(payload).catch(() => {}); else await interaction.reply(payload).catch(() => {}); }
}
