import { Client, Events, GatewayIntentBits, Partials } from 'discord.js';
import { env } from './config/env.js';
import { migrate, ensureGuild, run } from './database/index.js';
import { onInteraction } from './events/interaction-create.js';
import { handleAuditEntry, handleJoin, handleMessage } from './modules/security/index.js';
import { recordMessage } from './modules/community/index.js';
import { track } from './modules/analytics/index.js';
import { logger } from './utils/logger.js';
migrate();
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildModeration], partials: [Partials.Channel, Partials.Message] });
client.once(Events.ClientReady, (ready) => logger.info(`NEXUS online as ${ready.user.tag}`, { guilds: ready.guilds.cache.size }));
client.on(Events.GuildCreate, (guild) => { ensureGuild(guild.id); logger.info('Joined guild', { guildId: guild.id }); });
client.on(Events.GuildMemberAdd, async (member) => { ensureGuild(member.guild.id); track(member.guild.id, 'join', { userId: member.id }); run('INSERT INTO member_activity (guild_id,user_id,joined_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(guild_id,user_id) DO UPDATE SET joined_at = CURRENT_TIMESTAMP', [member.guild.id, member.id]); await handleJoin(member); });
client.on(Events.GuildMemberRemove, (member) => track(member.guild.id, 'leave', { userId: member.id }));
client.on(Events.MessageCreate, async (message) => { if (!message.guild || message.author.bot) return; track(message.guild.id, 'message', { channelId: message.channelId, userId: message.author.id }); recordMessage(message.guild.id, message.author.id); await handleMessage(message); });
client.on(Events.GuildAuditLogEntryCreate, (entry, guild) => handleAuditEntry(entry, guild));
client.on(Events.InteractionCreate, onInteraction);
client.on(Events.Error, (error) => logger.error('Discord client error', error));
process.on('unhandledRejection', (error) => logger.error('Unhandled rejection', error));
process.on('uncaughtException', (error) => { logger.error('Uncaught exception', error); });
await client.login(env.DISCORD_TOKEN);
